export { auth } from "./config.js";
export {
  UnauthorizedWorkspaceSessionError,
  confirmWorkspaceAdmission,
  confirmWorkspaceRevocationProjection,
  createPendingWorkspaceAdmission,
  requireCurrentWorkspaceSession,
  revokeWorkspaceAdmission,
  suspendUserAndRevokeSessions,
  type CurrentWorkspaceSession,
  type PendingWorkspaceAdmission,
} from "./workspace-session.js";
export {
  WorkspaceProjectionDeniedError,
  changeWorkspaceRole,
  confirmRevocationProjectionForActor,
  confirmRoleChangeProjection,
  confirmWorkspaceProjection,
  consumeMembershipTransitionGrant,
  consumeWorkspaceProjectionGrant,
  createWorkspaceWithPendingOwner,
  membershipInEdgeId,
  membershipOfEdgeId,
  mintMembershipTransitionGrant,
  mintWorkspaceProjectionGrant,
  revokeMembershipForActor,
  roleChangeDirection,
  PROJECTION_GRANT_PREFIX,
  PROJECTION_GRANT_TTL_SECONDS,
  type ConsumedProjectionGrant,
  type ConsumedTransitionGrant,
  type MembershipTransitionKind,
  type RoleChangeDirection,
  type WorkspaceProjectionGrant,
  type WorkspaceTransitionGrant,
} from "./workspace-projection.js";
